2024-08-15 09:27:56,864 - ClientTaskWorker - INFO - ClientTaskWorker started to run
2024-08-15 09:27:56,945 - CoreCell - INFO - site-2.simulate_job: created backbone external connector to tcp://localhost:53813
2024-08-15 09:27:56,945 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 ACTIVE tcp://localhost:53813] is starting
2024-08-15 09:27:56,948 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connection [CN00002 127.0.0.1:53830 => 127.0.0.1:53813] is created: PID: 71751
2024-08-15 09:27:57,274 - AuxRunner - INFO - registered aux handler for topic __end_run__
2024-08-15 09:27:57,274 - AuxRunner - INFO - registered aux handler for topic __do_task__
2024-08-15 09:27:57,274 - Cell - INFO - Register blob CB for channel='aux_communication', topic='*'
2024-08-15 09:27:57,781 - Cell - INFO - broadcast: channel='aux_communication', topic='__sync_runner__', targets=['server.simulate_job'], timeout=2.0
2024-08-15 09:27:57,786 - ClientRunner - INFO - [identity=site-2, run=simulate_job]: synced to Server Runner in 0.5102720260620117 seconds
2024-08-15 09:27:57,786 - AuxRunner - INFO - registered aux handler for topic RM.RELIABLE_REQUEST
2024-08-15 09:27:57,786 - AuxRunner - INFO - registered aux handler for topic RM.RELIABLE_REPLY
2024-08-15 09:27:57,787 - ReliableMessage - INFO - enabled reliable message: max_request_workers=20 query_interval=2.0
2024-08-15 09:27:57,788 - TaskScriptRunner - INFO - start task run() with full path: /Users/49751124/PycharmProjects/nvflare/NVFlare/examples/getting_started/pt/src/cifar10_fl.py
2024-08-15 09:27:57,788 - AuxRunner - INFO - registered aux handler for topic fed.event
2024-08-15 09:27:57,788 - ClientRunner - INFO - [identity=site-2, run=simulate_job]: client runner started
2024-08-15 09:27:57,789 - ClientTaskWorker - INFO - Initialize ClientRunner for client: site-2
2024-08-15 09:27:57,798 - Communicator - INFO - Received from simulator_server server. getTask: train size: 2.2KB (2189 Bytes) time: 0.008458 seconds
2024-08-15 09:27:57,798 - FederatedClient - INFO - pull_task completed. Task name:train Status:True 
2024-08-15 09:27:57,798 - ClientRunner - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job]: got task assignment: name=train, id=50f451e0-e6f7-468d-9e61-f29b1b9b0edd
2024-08-15 09:27:57,799 - ClientRunner - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=50f451e0-e6f7-468d-9e61-f29b1b9b0edd]: invoking task executor ScriptExecutor
2024-08-15 09:27:57,799 - ScriptExecutor - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=50f451e0-e6f7-468d-9e61-f29b1b9b0edd]: execute for task (train)
2024-08-15 09:27:57,809 - ScriptExecutor - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=50f451e0-e6f7-468d-9e61-f29b1b9b0edd]: send data to peer
2024-08-15 09:27:57,809 - ScriptExecutor - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=50f451e0-e6f7-468d-9e61-f29b1b9b0edd]: sending payload to peer
2024-08-15 09:27:57,809 - ScriptExecutor - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=50f451e0-e6f7-468d-9e61-f29b1b9b0edd]: Waiting for result from peer
2024-08-15 09:27:58,732 - nvflare.app_common.executors.task_script_runner - INFO - Files already downloaded and verified
2024-08-15 09:27:59,484 - nvflare.app_common.executors.task_script_runner - INFO - Files already downloaded and verified
2024-08-15 09:27:59,784 - nvflare.app_common.executors.task_script_runner - INFO - current_round=0
2024-08-15 09:27:59,799 - TaskScriptRunner - ERROR - Traceback (most recent call last):
  File "/Users/49751124/miniconda3/envs/nvflare/lib/python3.10/site-packages/nvflare/app_common/executors/task_script_runner.py", line 55, in run
    runpy.run_path(self.script_full_path, run_name="__main__")
  File "/Users/49751124/miniconda3/envs/nvflare/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/49751124/miniconda3/envs/nvflare/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/49751124/miniconda3/envs/nvflare/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/49751124/PycharmProjects/nvflare/NVFlare/examples/getting_started/pt/src/cifar10_fl.py", line 137, in <module>
    main()
  File "/Users/49751124/PycharmProjects/nvflare/NVFlare/examples/getting_started/pt/src/cifar10_fl.py", line 58, in main
    net.load_state_dict(input_model.params)
  File "/Users/49751124/miniconda3/envs/nvflare/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Net:
	Missing key(s) in state_dict: "conv1.weight", "conv1.bias", "conv2.weight", "conv2.bias", "fc1.weight", "fc1.bias", "fc2.weight", "fc2.bias", "fc3.weight", "fc3.bias". 
	Unexpected key(s) in state_dict: "linear.weight", "linear.bias". 

2024-08-15 09:27:59,799 - TaskScriptRunner - ERROR - fire abort event
2024-08-15 09:27:59,799 - InProcessClientAPI - ERROR - ask to abort job: reason: '/Users/49751124/PycharmProjects/nvflare/NVFlare/examples/getting_started/pt/src/cifar10_fl.py' is aborted, Traceback (most recent call last):
  File "/Users/49751124/miniconda3/envs/nvflare/lib/python3.10/site-packages/nvflare/app_common/executors/task_script_runner.py", line 55, in run
    runpy.run_path(self.script_full_path, run_name="__main__")
  File "/Users/49751124/miniconda3/envs/nvflare/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/49751124/miniconda3/envs/nvflare/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/49751124/miniconda3/envs/nvflare/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/49751124/PycharmProjects/nvflare/NVFlare/examples/getting_started/pt/src/cifar10_fl.py", line 137, in <module>
    main()
  File "/Users/49751124/PycharmProjects/nvflare/NVFlare/examples/getting_started/pt/src/cifar10_fl.py", line 58, in main
    net.load_state_dict(input_model.params)
  File "/Users/49751124/miniconda3/envs/nvflare/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Net:
	Missing key(s) in state_dict: "conv1.weight", "conv1.bias", "conv2.weight", "conv2.bias", "fc1.weight", "fc1.bias", "fc2.weight", "fc2.bias", "fc3.weight", "fc3.bias". 
	Unexpected key(s) in state_dict: "linear.weight", "linear.bias". 

2024-08-15 09:27:59,857 - InProcessClientAPI - ERROR - ask to abort job: reason: train' is aborted, abort_signal_triggered
2024-08-15 09:27:59,858 - ClientRunner - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=50f451e0-e6f7-468d-9e61-f29b1b9b0edd]: finished processing task
2024-08-15 09:27:59,858 - ClientRunner - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=50f451e0-e6f7-468d-9e61-f29b1b9b0edd]: try #1: sending task result to server
2024-08-15 09:27:59,858 - ClientRunner - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=50f451e0-e6f7-468d-9e61-f29b1b9b0edd]: checking task ...
2024-08-15 09:27:59,858 - Cell - INFO - broadcast: channel='aux_communication', topic='__task_check__', targets=['server.simulate_job'], timeout=5.0
2024-08-15 09:27:59,859 - ClientRunner - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=50f451e0-e6f7-468d-9e61-f29b1b9b0edd]: start to send task result to server
2024-08-15 09:27:59,859 - FederatedClient - INFO - Starting to push execute result.
2024-08-15 09:27:59,864 - Communicator - INFO -  SubmitUpdate size: 695B (695 Bytes). time: 0.004640 seconds
2024-08-15 09:27:59,864 - ClientRunner - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=50f451e0-e6f7-468d-9e61-f29b1b9b0edd]: task result sent to server
2024-08-15 09:27:59,864 - ClientTaskWorker - INFO - Finished one task run for client: site-2 interval: 2 task_processed: True
2024-08-15 09:27:59,920 - ClientRunner - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job]: received request from Server to end current RUN
2024-08-15 09:28:01,879 - FederatedClient - INFO - pull_task completed. Task name:__end_run__ Status:True 
2024-08-15 09:28:01,880 - ClientRunner - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job]: server asked to end the run
2024-08-15 09:28:01,880 - ClientRunner - INFO - [identity=site-2, run=simulate_job]: started end-run events sequence
2024-08-15 09:28:01,880 - ClientRunner - INFO - [identity=site-2, run=simulate_job]: ABOUT_TO_END_RUN fired
2024-08-15 09:28:01,880 - ClientRunner - INFO - [identity=site-2, run=simulate_job]: Firing CHECK_END_RUN_READINESS ...
2024-08-15 09:28:01,881 - InProcessClientAPI - WARNING - ask to stop job: reason: END_RUN received
2024-08-15 09:28:01,882 - ClientRunner - INFO - [identity=site-2, run=simulate_job]: END_RUN fired
2024-08-15 09:28:01,882 - ClientTaskWorker - INFO - End the Simulator run.
2024-08-15 09:28:01,882 - ClientTaskWorker - INFO - Clean up ClientRunner for : site-2 
2024-08-15 09:28:01,884 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connection [CN00002 Not Connected] is closed PID: 71751
